### ISSUE TITLE
Script error after first loop, looking for imobiledevice in wrong place (serviceMonitor)

### ISSUE THREAD

**Issue by CyanFireUK** [DiscordDigital/AltCheck-Reborn#1]
I am getting this error:

```
Set-Location : Cannot find path 'C:\AltCheck-Reborn\imobiledevice\imobiledevice' because it does not exist.
At C:\AltCheck-Reborn\AltCheck-Reborn.ps1:45 char:9
+         Set-Location -Path $iMobileDeviceFolder
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\AltCheck-Reb...e\imobiledevice:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

As you can see it's looking for AltCheck-Reborn\imobiledevice\imobiledevice, instead of AltCheck-Reborn\imobiledevice, It looks in the correct place when it runs for the first time, it's just subsequent loops that throw this error.

**Comment by DiscordDigital** [comment]
Hi

In case you want to use an absolute path, you can specify -iMobileDeviceFolder "C:\location-to-imobiledevice-folder" when running this script.

If you look into the script yourself, you'll see that Set-Location just uses the $iMobileDeviceFolder variable, inside of the loop.

I hope I can help, if not, let me know and we can take a closer look at this.

Best regards
DiscordDigital
